version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:${ZOO_KEEPER_VERSION}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - zookeeper_data_1:/var/lib/zookeeper/data
      - zookeeper_logs_1:/var/lib/zookeeper/log

  zookeeper-2:
    image: confluentinc/cp-zookeeper:${ZOO_KEEPER_VERSION}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
    volumes:
      - zookeeper_data_2:/var/lib/zookeeper/data
      - zookeeper_logs_2:/var/lib/zookeeper/log

  zookeeper-3:
    image: confluentinc/cp-zookeeper:${ZOO_KEEPER_VERSION}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 42181:2181
    volumes:
      - zookeeper_data_3:/var/lib/zookeeper/data
      - zookeeper_logs_3:/var/lib/zookeeper/log

  kafka-1:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data_1:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data_2:/var/lib/kafka/data

  kafka-3:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data_3:/var/lib/kafka/data

  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: "testDb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  zookeeper_data_1:
    driver: local
  zookeeper_logs_1:
    driver: local
  kafka_data_1:
    driver: local
  zookeeper_data_2:
    driver: local
  zookeeper_logs_2:
    driver: local
  kafka_data_2:
    driver: local
  zookeeper_data_3:
    driver: local
  zookeeper_logs_3:
    driver: local
  kafka_data_3:
    driver: local
  database:
    driver: local
