spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testDb
    username: root
    password: 123

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-
    consumer:
      group-id: group-a
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: ru.otr.kafka.dto.ConsumerDto
      enable-auto-commit: false
      isolation-level: read_committed


app:
  topic: topic
  messages: Hello World, Message is hidden, News of the day